import { Component, OnInit } from '@angular/core';
import {DoctorService} from '@src/app/doctor.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.css']
})
export class AutoGeneratedComponent implements OnInit {
  DoctorList =[];
  constructor(
    private doctorService : DoctorService,
    private router:Router
  ) { }
  // clearDoctor()
  // {
  //   this.doctorService.clearDoctors();
  //   this.router.navigate(['/auto-generated']);
  // }
  ngOnInit() {
    this.DoctorList= this.doctorService.getDoctors();
  }

}
