import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { DoctorRegisterationComponent } from '@src/app/doctor/doctor-registeration.component';

const routes: Routes = [
  {
    path: '',
    redirectTo: '/auto-generated',
    pathMatch: 'full',
  },
  {
    path: 'auto-generated',
    component: AutoGeneratedComponent,
  },
  {
    path: 'doc-reg',
    component: DoctorRegisterationComponent,
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
