import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
//import { NativeScriptModule } from 'nativescript-angular/nativescript.module';


import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { AppBootstrapModule } from '@src/app/app-bootstrap/app-bootstrap.module.tns';
import { DoctorRegisterationComponent } from '@src/app/doctor/doctor-registeration.component';
  

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    DoctorRegisterationComponent
  ],
  imports: [
    FormsModule,
    BrowserModule,
   // NativeScriptModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
